package debefix

// ResolveValue is a value that should be resolved by the user of the library in a callback.
// Usually this is used to return values generated by the database, like last insert id or created date.
type ResolveValue interface {
	isResolveValue()
}

// ResolveValueResolveData is a value to be resolved, with an option information parameter.
type ResolveValueResolveData struct {
	ResolveInfo any
}

// ResolveValueResolve is a value to be resolved, with an option information parameter.
func ResolveValueResolve(options ...ResolveValueResolveOption) ResolveValueResolveData {
	ret := ResolveValueResolveData{}
	for _, option := range options {
		option(&ret)
	}
	return ret
}

type ResolveValueResolveOption func(options *ResolveValueResolveData)

// WithResolveInfo adds a custom info for resolvers to use.
func WithResolveInfo(resolveInfo any) ResolveValueResolveOption {
	return func(options *ResolveValueResolveData) {
		options.ResolveInfo = resolveInfo
	}
}

func (v ResolveValueResolveData) isResolveValue() {}
